# This file is part of lyx2lyx
# Copyright (C) 2025 The LyX team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

"""Convert files to the file format generated by lyx 2.6"""

import re

# Uncomment only what you need to import, please (lyx2lyx_tools):
#    convert_info_insets,
#    get_ert,
#    hex2ratio,
#    insert_to_preamble,
#    latex_length,
#    length_in_bp,
#    lyx2latex,
#    lyx2verbatim,
#    put_cmd_in_ert,
#    revert_flex_inset,
#    revert_flex_inset,
#    revert_font_attrs,
#    revert_language
#    str2bool
from lyx2lyx_tools import (
    add_to_preamble
)

# Uncomment only what you need to import, please (parser_tools):
#    check_token,
#    count_pars_in_inset,
#    del_complete_lines,
#    del_value,
#    find_complete_lines, 
#    find_end_of,
#    find_end_of_layout,
#    find_substring,
#    find_token_backwards,
#    find_token_exact,
#    find_tokens,
#    get_containing_inset,
#    get_containing_layout,
#    get_bool_value,
#    get_option_value,
#    set_bool_value,
#    is_in_inset
from parser_tools import (
    del_token,
    find_end_of_inset,
    find_re,
    find_token,
    get_quoted_value,
    get_value
)

####################################################################
# Private helper functions

# Provide, on reversion, preamble definitions for elements that
# are supported via CrossrefNeedDef
# prfx: ref prefix [string]
# form: PrettyFormat, e.g., "Example|Examples (##)" [string]
# counter: counter name [string]
# alias: alias definitions for zref and cleveref in keyval form,
#        type/latexname=realcounter
#        e.g. "env/covexamples=equation" [list]
def revert_xref_defs(document, prfx, form, counter, alias):
    """Revert supported xref defs to preamble code"""
    package = "refstyle"
    i = find_token(document.header, "\\crossref_package", 0)
    if i == -1:
        document.warning("Missing \\crossref_package header!")
    else:
        package = get_value(document.header, "\\crossref_package", i)

    have_ref = False
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset CommandInset ref", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of reference inset at line %d!!" % (i))
            i += 1
            continue

        k = find_token(document.body, "LatexCommand formatted", i, j)
        if k == -1:
            i += 1
            continue

        label = get_quoted_value(document.body, "reference", i, j)
        if not ":" in label:
            i += 1
            continue

        prefix = label.split(":", 1)[0]
        if prefix == prfx:
            have_ref = True
        i += 1

    if not have_ref:
        return

    pr_def = []
    pr_xdef = []
    forms = form.split("|", 1)
    form_sg = forms[0]
    form_pl = forms[1].split()[0]
    form_nr = forms[1].split()[1]
    br_left = ""
    br_right = ""
    if not form_nr.startswith("##"):
        br_left = form_nr.split("#", 1)[0]
    if not form_nr.endswith("##"):
        br_right = form_nr.split("##")[-1]
        
    if "prettyref" in package:
        pr_def = ["\\newrefformat{" + prfx + "}{" + form_sg + "~" + br_left + "\\ref{#1}" + br_right + "}"]
    elif package == "refstyle":
        pr_def = ["\\newref{" + prfx + "}{",
                  "name = {" + form_sg.lower() + "~},",
                  "names = {" + form_pl.lower() + "~},",
                  "Name = {" + form_sg + "~},",
                  "Names = {" + form_pl + "~},",
                  "refcmd = {" + br_left + "\\ref{#1}" + br_right + "}",
                  "}"]
    elif package == "cleveref":
        pr_def = ["\\usepackage{cleveref}",
                  "\\crefname{" + counter + "}{" + form_sg.lower() + "}{" + form_pl.lower() + "}",
                  "\\Crefname{" + counter + "}{" + form_sg + "}{" + form_pl + "}",
                  "\\creflabelformat{" + counter + "}{\\textup{" + br_left + "#2#1#3" + br_right + "}}"]
        for al in alias:
            if not "=" in al:
                continue
            pr_xdef += ["\\AddToHook{" +  al.split("=")[0] + "/begin}{%",
                       "\\crefalias{" + al.split("=")[1] + "}{" + counter + "}",
                       "}"]
    elif package == "zref":
        pr_def = ["\\usepackage{zref-clever}",
                  "\\zcRefTypeSetup{" + counter + "}{",
                  "Name-sg = " + form_sg + " ,",
                  "name-sg = " + form_sg.lower() + " ,",
                  "Name-pl = " + form_pl + " ,",
                  "name-pl = " + form_pl.lower() + " ,",
                  "refbounds-first-sg = {," + br_left + "," + br_right + ",} ,",
                  "refbounds = {," + br_left + ",,," + br_right + ",} ,",
                  "}"]
        for al in alias:
            if not "=" in al:
                continue
            pr_xdef += ["\\AddToHook{" +  al.split("=")[0] + "/begin}{%",
                       "\\zcsetup{countertype={" + al.split("=")[1] + "}{" + counter + "}}",
                       "}"]
    
    if len(pr_def) > 0:
        add_to_preamble(
                document,
                pr_def
            )
    if len(pr_xdef) > 0:
        add_to_preamble(
                document,
                pr_xdef
            )



###############################################################################
###
### Conversion and reversion routines
###
###############################################################################


def revert_ling_xrefs(document):
    """Revert xref defs of linguistics module"""

    if not "linguistics" in document.get_module_list():
        return

    # examples
    revert_xref_defs(document, "lex", "Example|Examples (##)", "covex", ["env/covsubexamples=enumi", "env/covexamples=equation"])
    # tableaux
    revert_xref_defs(document, "tbl", "Tableau|Tableaux ##", "tableau", [""])


def convert_refname(document):
    "Remove the long unused name crossref parameter"

    # Remove name CommandInset ref param.
    # This is unused as of 2020 (fd6e14414f272)
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset CommandInset ref", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of reference inset at line %d!!" % (i))
            i += 1
            continue

        del_token(document.body, "name", i, j)
        i += 1

    # Same for InsetMathRef where this was an optional argument
    regexp = re.compile(r"(.*)(\\[a-zA-Z]*ref|formatted)(\[\w+\])(.*)")
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset Formula", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of inset at line %d of body!" % i)
            i += 1
            continue
        k = find_re(document.body, regexp, i, j)
        if k != -1:
            m = regexp.match(document.body[k])
            if m:
                document.body[k] = m.group(1) + m.group(2) + m.group(4)
        i = j


##
# Conversion hub
#

supported_versions = ["2.6.0", "2.6"]
convert = [
    [644, [convert_refname]]
]


revert = [
    [643, [revert_ling_xrefs]]
]


if __name__ == "__main__":
    pass
