# This file is part of lyx2lyx
# Copyright (C) 2025 The LyX team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

"""Convert files to the file format generated by lyx 2.6"""

import re

# Uncomment only what you need to import, please (lyx2lyx_tools):
#    convert_info_insets,
#    get_ert,
#    hex2ratio,
#    insert_to_preamble,
#    latex_length,
#    length_in_bp,
#    lyx2latex,
#    lyx2verbatim,
#    revert_flex_inset,
#    revert_flex_inset,
#    revert_font_attrs,
#    revert_language
#    str2bool
from lyx2lyx_tools import (
    add_to_preamble,
    put_cmd_in_ert
)

# Uncomment only what you need to import, please (parser_tools):
#    check_token,
#    count_pars_in_inset,
#    del_complete_lines,
#    del_value,
#    find_complete_lines, 
#    find_end_of,
#    find_substring,
#    find_token_exact,
#    find_tokens,
#    get_bool_value,
#    get_option_value,
#    set_bool_value,
#    is_in_inset
from parser_tools import (
    del_token,
    find_end_of_inset,
    find_end_of_layout,
    find_end_of_sequence,
    find_re,
    find_token,
    find_token_backwards,
    get_containing_inset,
    get_containing_layout,
    get_quoted_value,
    get_value
)

####################################################################
# Private helper functions

# Provide, on reversion, preamble definitions for elements that
# are supported via CrossrefNeedDef
# prfx: ref prefix [string]
# form: PrettyFormat, e.g., "Example|Examples (##)" [string]
# counter: counter name [string]
# alias: alias definitions for zref and cleveref in keyval form,
#        type/latexname=realcounter
#        e.g. "env/covexamples=equation" [list]
def revert_xref_defs(document, prfx, form, counter, alias):
    """Revert supported xref defs to preamble code"""
    package = "refstyle"
    i = find_token(document.header, "\\crossref_package", 0)
    if i == -1:
        document.warning("Missing \\crossref_package header!")
    else:
        package = get_value(document.header, "\\crossref_package", i)

    have_ref = False
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset CommandInset ref", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of reference inset at line %d!!" % (i))
            i += 1
            continue

        k = find_token(document.body, "LatexCommand formatted", i, j)
        if k == -1:
            i += 1
            continue

        label = get_quoted_value(document.body, "reference", i, j)
        if not ":" in label:
            i += 1
            continue

        prefix = label.split(":", 1)[0]
        if prefix == prfx:
            have_ref = True
        i += 1

    if not have_ref:
        return

    pr_def = []
    pr_xdef = []
    forms = form.split("|", 1)
    form_sg = forms[0]
    form_pl = forms[1].split()[0]
    form_nr = forms[1].split()[1]
    br_left = ""
    br_right = ""
    if not form_nr.startswith("##"):
        br_left = form_nr.split("#", 1)[0]
    if not form_nr.endswith("##"):
        br_right = form_nr.split("##")[-1]
        
    if "prettyref" in package:
        pr_def = ["\\newrefformat{" + prfx + "}{" + form_sg + "~" + br_left + "\\ref{#1}" + br_right + "}"]
    elif package == "refstyle":
        pr_def = ["\\newref{" + prfx + "}{",
                  "name = {" + form_sg.lower() + "~},",
                  "names = {" + form_pl.lower() + "~},",
                  "Name = {" + form_sg + "~},",
                  "Names = {" + form_pl + "~},",
                  "refcmd = {" + br_left + "\\ref{#1}" + br_right + "}",
                  "}"]
    elif package == "cleveref":
        pr_def = ["\\usepackage{cleveref}",
                  "\\crefname{" + counter + "}{" + form_sg.lower() + "}{" + form_pl.lower() + "}",
                  "\\Crefname{" + counter + "}{" + form_sg + "}{" + form_pl + "}",
                  "\\creflabelformat{" + counter + "}{\\textup{" + br_left + "#2#1#3" + br_right + "}}"]
        for al in alias:
            if not "=" in al:
                continue
            pr_xdef += ["\\AddToHook{" +  al.split("=")[0] + "/begin}{%",
                       "\\crefalias{" + al.split("=")[1] + "}{" + counter + "}",
                       "}"]
    elif package == "zref":
        pr_def = ["\\usepackage{zref-clever}",
                  "\\zcRefTypeSetup{" + counter + "}{",
                  "Name-sg = " + form_sg + " ,",
                  "name-sg = " + form_sg.lower() + " ,",
                  "Name-pl = " + form_pl + " ,",
                  "name-pl = " + form_pl.lower() + " ,",
                  "refbounds-first-sg = {," + br_left + "," + br_right + ",} ,",
                  "refbounds = {," + br_left + ",,," + br_right + ",} ,",
                  "}"]
        for al in alias:
            if not "=" in al:
                continue
            pr_xdef += ["\\AddToHook{" +  al.split("=")[0] + "/begin}{%",
                       "\\zcsetup{countertype={" + al.split("=")[1] + "}{" + counter + "}}",
                       "}"]
    
    if len(pr_def) > 0:
        add_to_preamble(
                document,
                pr_def
            )
    if len(pr_xdef) > 0:
        add_to_preamble(
                document,
                pr_xdef
            )



###############################################################################
###
### Conversion and reversion routines
###
###############################################################################


def revert_ling_xrefs(document):
    """Revert xref defs of linguistics module"""

    if not "linguistics" in document.get_module_list():
        return

    # examples
    revert_xref_defs(document, "lex", "Example|Examples (##)", "covex", ["env/covsubexamples=enumi", "env/covexamples=equation"])
    # tableaux
    revert_xref_defs(document, "tbl", "Tableau|Tableaux ##", "tableau", [""])


def convert_refname(document):
    "Remove the long unused name crossref parameter"

    # Remove name CommandInset ref param.
    # This is unused as of 2020 (fd6e14414f272)
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset CommandInset ref", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of reference inset at line %d!!" % (i))
            i += 1
            continue

        del_token(document.body, "name", i, j)
        i += 1

    # Same for InsetMathRef where this was an optional argument
    regexp = re.compile(r"(.*\\)(ref|pageref|cpageref|vref|vpageref|formatted|prettyref|eqref|nameref|labelonly)(\[\w+\])(.*)")
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset Formula", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of inset at line %d of body!" % i)
            i += 1
            continue
        k = find_re(document.body, regexp, i, j)
        if k != -1:
            m = regexp.match(document.body[k])
            if m:
                document.body[k] = m.group(1) + m.group(2) + m.group(4)
        i = j


def revert_mathref(document):
    "Revert advanced formatted refs to LaTeX"

    package = "refstyle"
    i = find_token(document.header, "\\crossref_package", 0)
    if i == -1:
        document.warning("Missing \\crossref_package header!")
    else:
        package = get_value(document.header, "\\crossref_package", i)

    regexp = re.compile(r"(.*\\)(ref|pageref|cpageref|vref|vpageref|formatted|prettyref|eqref|nameref|labelonly)(\[|\{)(.*)")
    # \cmd[opt]{arg}[opt]
    reg_opt1 = re.compile(r"(.*\\)(ref|pageref|cpageref|vref|vpageref|formatted|prettyref|eqref|nameref|labelonly)(\[[^\]]+\])(\{[^\}]+\})(\[[^\]]+\])(.*)")
    # \cmd[opt]{arg}
    reg_opt2 = re.compile(r"(.*\\)(ref|pageref|cpageref|vref|vpageref|formatted|prettyref|eqref|nameref|labelonly)(\[[^\]]\])(\{[^\}]+\})(.*)")
    # \cmd{arg}[opt]
    reg_opt3 = re.compile(r"(.*\\)(ref|pageref|cpageref|vref|vpageref|formatted|prettyref|eqref|nameref|labelonly)(\{[^\}]+\})(\[[^\]]+\])(.*)")
    need_zref_clever = False
    need_zref_vario = False
    need_cleveref = False
    need_refstyle = False
    need_varioref = False
    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset Formula", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of inset at line %d of body!" % i)
            i += 1
            continue
        k = find_re(document.body, regexp, i, j)
        if k == -1:
            i = j
            continue
        
        pretext = ""
        posttext = ""
        cmd = ""
        opt = ""
        arg = ""
        features = []
        l = i
        while True:
            m = reg_opt1.match(document.body[k])
            if m:
                pretext = m.group(1)
                cmd = m.group(2)
                opt = m.group(3)
                arg = m.group(4)
                features = m.group(5)[1:-1].split(",")
                posttext = m.group(6)
            else:
                m = reg_opt2.match(document.body[k])
                if m:
                    pretext = m.group(1)
                    cmd = m.group(2)
                    opt = m.group(3)
                    arg = m.group(4)
                    posttext = m.group(5)
                else:
                    m = reg_opt3.match(document.body[k])
                    if m:
                        pretext = m.group(1)
                        cmd = m.group(2)
                        arg = m.group(3)
                        features = m.group(4)[1:-1].split(",")
                        posttext = m.group(5)
                    else:
                        l += 1
                        k = find_re(document.body, regexp, l, j)
                        if k == -1 or l == j:
                            i = j
                            break

            arguments = arg[1:-1].split(",")
            
            use_nolink = "nolink" in features and find_token(document.header, "\\use_hyperref true", 0) != -1

            # labelonly
            if cmd == "labelonly":
                # strip prefixes if requested
                if "noprefix" in features:
                    npargs = []
                    for argu in arguments:
                        if ":" in argu:
                            npargs.append(argu.split(":", 1)[1])
                        else:
                            npargs.append(argu)
                    arg = "{" + ",".join(npargs) + "}"
                document.body[k] = pretext + cmd + arg + posttext
                continue

            use_range = False
            if len(arguments) == 2 and (cmd == "vref" or cmd == "vpageref") and package != "zref":
                use_range = True
            elif len(arguments) != 2 or "range" not in features:
                use_range = False
            elif cmd == "vref" or cmd == "vpageref" or cmd == "cpageref" or (cmd == "formatted" and  "prettyref" not in package):
                use_range = True
            
            if cmd == "vref" or cmd == "vpageref":
                if not use_range and "nolink" not in features and (package != "zref" or ("caps" not in features and opt == "")):
                    document.body[k] = pretext + cmd + arg + posttext
                    continue
                if package == "zref":
                    cmd = "z" + cmd
                    need_zref_vario = True
                else:
                    need_varioref = True
                if use_range:
                    cmd += "range"
                if use_nolink:
                    cmd += "*"
                realopt = []
                if package == "zref":
                    realopt = opt[1:-1].split(",")
                    if "caps" in features:
                        realopt.append("S")
                    realopt = list(filter(None, realopt))
                    if len(realopt) > 0:
                        cmd += "[" + ",".join(realopt) + "]"
                first = True
                cmd += "{"
                for argu in arguments:
                    if not first:
                        if use_range:
                            cmd += "}{"
                        else:
                            cmd += ","
                    first = False
                    cmd += argu
                cmd += "}"
                document.body[k] = pretext + cmd + posttext
                continue

            # cpageref
            if cmd == "cpageref":
                if package == "cleveref":
                    if not use_range and "caps" not in features:
                        # just remove the opts
                        document.body[k] = pretext + cmd + arg + posttext
                        continue
                    need_cleveref = True
                    if "caps" in features:
                        cmd = cmd.title()
                    first = True
                    cmd += "{"
                    for argu in arguments:
                        if not first:
                            if use_range:
                                cmd += "}{"
                            else:
                                cmd += ","
                            first = False
                        cmd += argu
                    cmd += "}"
                    document.body[k] = pretext + cmd + posttext
                    continue
                if package == "zref":
                    if not use_range and "caps" not in features and not use_nolink:
                        # just remove the opts
                        document.body[k] = pretext + cmd + arg + posttext
                        continue
                    need_zref_clever = True
                    cmd = "z" + cmd
                    if use_nolink:
                        cmd += "*"
                    realopt = opt[1:-1].split(",")
                    if "caps" in features:
                        realopt.append("S")
                    if use_range:
                        realopt.append("range")
                    realopt = list(filter(None, realopt))
                    if len(realopt) > 0:
                        cmd += "[" + ",".join(realopt) + "]"
                    first = True
                    cmd += "{"
                    for argu in arguments:
                        if not first:
                            if use_range:
                                cmd += "}{"
                            else:
                                cmd += ","
                            first = False
                        cmd += argu
                    cmd += "}"
                    document.body[k] = pretext + cmd + posttext
                    continue
                else:
                    if "nolink" in features:
                        cmd = "pageref*"
                    document.body[k] = pretext + cmd + arg + posttext
                    continue

            if len(arguments) > 1 and package == "cleveref":
                if cmd == "ref":
                    need_cleveref = True
                    document.body[k] = pretext + "labelcref" + arg + posttext
                    continue
                if cmd == "pageref":
                    need_cleveref = True
                    document.body[k] = pretext + "labelcpageref" + arg + posttext
                    continue

            if len(arguments) > 1 and package == "zref":
                if cmd == "ref" or cmd == "pageref":
                    need_zref_clever = True
                    cmd = "zcref"
                    if use_nolink:
                        cmd += "*"
                    realopt = opt[1:-1].split(",")
                    if "caps" in features:
                        realopt.append("noname")
                        if cmd == "pageref":
                            realopt.append("page")
                    realopt = list(filter(None, realopt))
                    if len(realopt) > 0:
                        cmd += "[" + ",".join(realopt) + "]"
                    document.body[k] = pretext + cmd + arg + posttext
                    continue

            # formatted
            if cmd == "formatted":
                # prettyref
                if "prettyref" in package:
                    cmd = "prettyref"
                # refstyle
                if package == "refstyle":
                    if len(arguments) == 1 and not "plural" in features and not "caps" in features:
                        document.body[k] = pretext + cmd + arg + posttext
                        continue
                    need_refstyle = True
                    npargs = []
                    prfx = ""
                    for argu in arguments:
                        document.warning("argu: %s" % argu)
                        if ":" in argu:
                            npargs.append(argu.split(":", 1)[1])
                            if prfx == "":
                                prfx = argu.split(":", 1)[0]
                        else:
                            npargs.append(argu)
                    cmd = prfx + "ref"
                    if "caps" in features:
                        cmd = cmd.title()
                    if "plural" in features:
                        cmd += "[s]"
                    arg = "{" + ",".join(npargs) + "}"
                    document.body[k] = pretext + cmd + arg + posttext
                    continue
                # cleveref
                if package == "cleveref":
                    if len(arguments) == 1 and not "caps" in features:
                        document.body[k] = pretext + cmd + arg + posttext
                        continue
                    need_cleveref = True
                    if "caps" in features:
                        cmd = "Cref"
                    else:
                        cmd = "cref"
                    if use_range:
                        cmd += "range"
                    if use_nolink:
                        cmd += "*"
                    document.body[k] = pretext + cmd + arg + posttext
                    continue
                # zref
                if package == "zref":
                    if len(arguments) == 1 and not "caps" in features:
                        document.body[k] = pretext + cmd + arg + posttext
                        continue
                    need_zref_clever = True
                    cmd = "zcref"
                    realopt = opt[1:-1].split(",")
                    if "caps" in features:
                        realopt.append("S")
                    if use_range:
                        realopt.append("range") 
                    if use_nolink:
                        cmd += "*"
                    realopt = list(filter(None, realopt))
                    if len(realopt) > 0:
                        cmd += "[" + ",".join(realopt) + "]"
                    document.body[k] = pretext + cmd + arg + posttext
                    continue

            # Rest (\ref, \eqref, \prettyref
            if len(arguments) > 1:
                cmds = []
                first = True
                for argu in arguments:
                    if first:
                        cmds.append(cmd + "{" + argu + "}")
                        first = False
                    else:
                        cmds.append("\\" + cmd + "{" + argu + "}")
                cmd = ", ".join(cmds)
                document.body[k] = pretext + cmd + posttext
                continue
            # remove the opts
            document.body[k] = pretext + cmd + arg + posttext
            continue

        i = j

    # preamble
    if need_zref_clever:
        add_to_preamble(
            document,
            ["\\usepackage{zref-clever}"]
        )
    if need_zref_vario:
        add_to_preamble(
            document,
            ["\\usepackage{zref-vario}"]
        )
    if need_cleveref:
        add_to_preamble(
            document,
            ["\\usepackage{cleveref}"]
        )
    if need_varioref:
        add_to_preamble(
            document,
            ["\\usepackage{varioref}"]
        )
    if need_refstyle:
        add_to_preamble(
            document,
            ["\\usepackage{refstyle}"]
        )


def revert_contextual_breaks(document):
    "Revert contextual breaks in multicol and frame to LaTeX"

    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset Newpage contextual", i)
        if i == -1:
            break
        j = find_end_of_inset(document.body, i)
        if j == -1:
            document.warning("Can't find end of Newpage inset at line %d!!" % (i))
            i += 1
            continue
        # get the containing layout
        lay = get_containing_layout(document.body, i)
        if lay == False:
            document.warning("No containing layout found!")
            i += 1
            continue
        beglay = lay[1]
        endlay = find_end_of_layout(document.body, beglay)
        if endlay == False:
            document.warning("Cannot find endlayout!")
            i += 1
            continue    
        # check whether this is Frame
        if lay[0] == "Frame":
            document.body[i : j + 1] = put_cmd_in_ert("\\framebreak{}")
            i += 1
            continue
        # next try inset
        inInset = get_containing_inset(document.body, beglay)
        if inInset and inInset[0] == "Flex Multiple Columns":
            endInset = find_end_of_inset(document.body, inInset[1])
            if endInset == -1:
                 document.warning("Can't find end of multicol inset at line %d!!" % (inInset))
                 i += 1
                 continue
            document.body[i : j + 1] = put_cmd_in_ert("\\columnbreak{}")
            i += 1
            continue
        else:
            # try layout
            handled = False
            k = i - 1
            while True:
                k = find_token_backwards(document.body, "\\begin_layout Frame", k)
                if k == -1:
                    break
                l = find_end_of_sequence(document.body, k)
                if l > i:
                    document.body[i : j + 1] = put_cmd_in_ert("\\framebreak{}")
                    i += 1
                    handled = True
                    break
                k -= 1
                continue
            if not handled:
                del document.body[beglay - 1 : endlay + 1]


def convert_textbreaks(document):
    "Convert Inset Textbreak to Inset Newpage"

    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset Newpage", i)
        if i == -1:
            break
        document.body[i] = document.body[i].replace("\\begin_inset Newpage", "\\begin_inset Textbreak")
        i += 1
        continue

def revert_textbreaks(document):
    "Revert Inset Textbreak to Inset Newpage"

    i = 0
    while True:
        i = find_token(document.body, "\\begin_inset Textbreak", i)
        if i == -1:
            break
        document.body[i] = document.body[i].replace("\\begin_inset Textbreak", "\\begin_inset Newpage")
        i += 1
        continue

##
# Conversion hub
#

supported_versions = ["2.6.0", "2.6"]
convert = [
    [644, [convert_refname]],
    [645, []],
    [646, []],
    [647, [convert_textbreaks]]
]


revert = [
    [646, [revert_textbreaks]],
    [645, [revert_contextual_breaks]],
    [644, [revert_mathref]],
    [643, [revert_ling_xrefs]]
]


if __name__ == "__main__":
    pass
