#!/bin/bash
# This script builds a maintainance LyX distribution according to 
# the procedure outlined at:
#   http://wiki.lyx.org/Devel/ReleaseProcedure
# It also includes several other tests, to make sure the packages
# works as it should.

#DEBUG=echo;

#########################################################
# A few variables need to be set, here at the top. 
# The script should not need any other customization.
#
# Where we will do our work
BASE="/cvs/lyx/lyx-release";
# Where our git repository lives
SRCDIR="/cvs/lyx/lyx-stable";
# editor 
if [ -z "$EDITOR" ]; then EDITOR=vi; fi


#########################################################
# Option variables

# Options to make, when we compile
MAKEOPTS="-j12";
# Compile?
COMPILE="YES";
# Make patch file?
PATCH="YES";

function usage() {
echo "lyx-build [-C] [-m MAKEARGS]]";
echo " -C: Do not test compilation";
echo " -m MAKEARGS: Arguments for make";
}

while getopts ":Cm:h" opt; do
  case $opt in
    C )   COMPILE="";; # don't test compilation
    m )   MAKEOPTS="$OPTARG";;
    h )   usage; exit 0;;
    \? )  echo "Unknown option $opt"; usage; exit 1;;
  esac
done
shift $(($OPTIND - 1));

# Determine LyX version
cd $SRCDIR/
VERSION=$(head configure.ac | grep AC_INIT | perl -e 'while (<>) {m/AC_INIT\(\[LyX\],\[([^,]+)\]/; print $1;}');

# Development release?
DEVEL_RELEASE="";

# If the version in configure.ac is e.g. "2.3.4dev", then we are building
# a development release.
PKG_VERSION=${VERSION%dev};
if [ "$VERSION" != "$PKG_VERSION" ]; then
	CURHASH=$(git rev-parse HEAD);
	# Eight chars should be enough
	CURHASH=${CURHASH:0:8};
	# New version is e.g. 2.3.4-12649348
	PKG_VERSION="$VERSION-$CURHASH";
	PATCH="";
fi

echo "This is version $PKG_VERSION.";
echo -n "Ready to build source packages...";
read

echo "Exporting clean tree...";
$DEBUG rm -Rf $BASE/lyx-export/
$DEBUG git checkout-index -a -f --prefix=$BASE/lyx-export/
$DEBUG cd $BASE/lyx-export/
$DEBUG ./autogen.sh
$DEBUG rm -Rf $BASE/lyx-build/
$DEBUG mkdir $BASE/lyx-build/
$DEBUG cd $BASE/lyx-build/

echo "Building distribution...";
$DEBUG $BASE/lyx-export/configure --enable-build-type=rel --enable-qt5
if ! $DEBUG make dist; then
  echo "Couldn't make distribution!";
  exit 1;
fi

echo "Packages created:";

# This will happen with development releases
if [ ! -f "lyx-$PKG_VERSION.tar.xz" ]; then
	$DEBUG mv "lyx-$VERSION.tar.xz" "lyx-$PKG_VERSION.tar.xz" || exit 1;
fi

$DEBUG ln lyx-$PKG_VERSION.tar.{gz,xz} $BASE/ || exit 1;

echo -n "Ready to build signatures...";
read

$DEBUG gpg -b lyx-$VERSION.tar.xz

echo "Signatures created:"
$DEBUG ln lyx-$VERSION.tar.*.sig $BASE;

if [ -n "$COMPILE" ]; then
	echo -n "Ready to test compilation...";
	read

	$DEBUG rm -Rf $BASE/lyx-test/
	$DEBUG mkdir $BASE/lyx-test/
	$DEBUG cd $BASE/lyx-test/
	$DEBUG tar -xvf $BASE/lyx-build/lyx-$VERSION.tar.xz
	if ! $DEBUG cd lyx-$PKG_VERSION; then
		echo "Unable to enter build directory!";
		exit 1;
	fi

	$DEBUG ./configure --enable-build-type=rel --enable-qt5

	if $DEBUG make $MAKEOPTS; then
		echo "Compilation complete.";
		echo -n "Ready to run LyX...";
		read;
		$DEBUG src/lyx -userdir /tmp/lyx-test;
	else
		echo "Compilation errors!!";
		exit 1;
	fi
fi
