# Sets the order of the main theorem environments
# Author: Richard Kimberly Heck

Format 116

Style Theorem
	CopyStyle	Theorem*
	DependsOn	Theorem*
End

Style Corollary
	CopyStyle	Corollary*
	DependsOn	Corollary*
End

Style Lemma
	CopyStyle	Lemma*
	DependsOn	Lemma*
End

Style Proposition
	CopyStyle	Proposition*
	DependsOn	Proposition*
End

Style Conjecture
	CopyStyle	Conjecture*
	DependsOn	Conjecture*
End

Style Definition
	CopyStyle	Definition*
	DependsOn	Definition*
End

Style Example
	CopyStyle	Example*
	DependsOn	Example*
End

Style Solution
	CopyStyle	Solution*
	DependsOn	Solution*
End

Style Problem
	CopyStyle	Problem*
	DependsOn	Problem*
End

Style Exercise
	CopyStyle	Exercise*
	DependsOn	Exercise*
End

Style Remark
	CopyStyle	Remark*
	DependsOn	Remark*
End

Style Claim
	CopyStyle	Claim*
	DependsOn	Claim*
End
